### ISSUE TITLE
Invalid config for rule @typescript-eslint/array-type

### ISSUE THREAD

**Issue by gbahamondezc** [ridedott/eslint-config#127]
Hi! , thanks for this super interesting ESLint configuration ;)

Trying to use in my projects gives me the error  **"Configuration for rule @typescript-eslint/array-type is invalid: Value array-simple should be object."**

Taking a look to the code,  `rules/typescript.js:3` seems to be the problem, the [documentation says](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/array-type.md) that it expects an object but it's receiving a string.

<img width="962" alt="Screen Shot 2019-08-17 at 9 18 37 AM" src="https://user-images.githubusercontent.com/22915623/63212677-310d4b80-c0d6-11e9-9bb8-3a0e0c34d55d.png">

**Comment by merlinnot** [comment]
Hi, you're right. This was changed in `@typescript-eslint` v2, which we didn't yet upgrade to.

I'll add more documentation on how to use ESLint with local modules, so it's covered.

**Comment by gbahamondezc** [comment]
Great, thanks :)
